/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sprint2;

import sprint2.controllers.MessageController;
import sprint2.entity.Etudiant;
import sprint2.entity.Message;
import jade.core.AID;
import jade.core.Agent;
import jade.domain.AMSService;
import jade.domain.FIPAAgentManagement.AMSAgentDescription;
import jade.domain.FIPAAgentManagement.SearchConstraints;
import jade.gui.GuiEvent;
import jade.lang.acl.ACLMessage;
import jade.wrapper.ContainerController;
import jade.wrapper.ControllerException;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
import sprint1.UserAgent;
import sprint2.agentAccueil;
import sprint3.GoogleResult;
import sprint3.LeaderOpinion;


/**
 *
 * @author lenovo
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Accueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel3 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        directoryLabel = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageReceivePanel = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        messageDownload = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        contactsScrollPane = new javax.swing.JScrollPane();
        contactsPanel2 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        chooseFile = new javax.swing.JButton();
        contactTextField = new javax.swing.JTextField();
        filePathLabel = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        sentMessages = new javax.swing.JTextArea();
        jButton21 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchTextArea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        clickLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        userLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        panel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 3, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 153));
        jLabel21.setText("Bienvenue Dans Votre Espace Personnel");
        jLabel21.setToolTipText("");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, 30));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane5.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane5.setForeground(new java.awt.Color(0, 153, 153));
        jTabbedPane5.setToolTipText("HH\n");
        jTabbedPane5.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jTabbedPane5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTabbedPane5.setName("ENVOIE\n"); // NOI18N

        jPanel7.setBackground(new java.awt.Color(235, 236, 255));
        jPanel7.setForeground(new java.awt.Color(153, 153, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(51, 51, 51));
        jButton9.setText("Parcourir");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 90, 30));

        directoryLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directoryLabelActionPerformed(evt);
            }
        });
        jPanel7.add(directoryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 265, 20));

        jPanel15.setBackground(new java.awt.Color(59, 184, 220,100));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 213, 255), 3));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Documents Reçus");
        jPanel15.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 8, -1, -1));

        messageReceivePanel.setBackground(new java.awt.Color(255, 255, 255));
        messageReceivePanel.setLayout(new javax.swing.BoxLayout(messageReceivePanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(messageReceivePanel);

        jPanel15.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 240, 130));

        jPanel7.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 300, 210));

        jLabel40.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 153, 153));
        jLabel40.setText("Boite de réception ");
        jLabel40.setToolTipText("");
        jPanel7.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 30));

        jPanel19.setBackground(new java.awt.Color(59, 184, 220,100));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 220, 255), 3));

        jLabel37.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 153, 153));
        jLabel37.setText("Contacts");
        jPanel19.add(jLabel37);

        jLabel38.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel19.add(jLabel38);

        jLabel43.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel19.add(jLabel43);

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jTextArea8.setBorder(null);
        jTextArea8.setMargin(new java.awt.Insets(80, 25, 1, 100));
        jScrollPane8.setViewportView(jTextArea8);

        jPanel19.add(jScrollPane8);

        jPanel7.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 310, 210));
        jPanel7.add(messageDownload, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 300, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/flat-university-concept_23-2148172741.jpg"))); // NOI18N
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        jTabbedPane5.addTab("Réception", jPanel7);

        jPanel16.setBackground(new java.awt.Color(234, 239, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 213, 255)));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(59, 184, 220,100));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 220, 255), 3));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 153, 153));
        jLabel32.setText("Contacts");
        jPanel17.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 8, -1, -1));

        jLabel33.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel17.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 18, -1, -1));

        jLabel34.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel17.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 18, -1, -1));

        contactsPanel2.setBackground(new java.awt.Color(255, 255, 255));
        contactsPanel2.setLayout(new javax.swing.BoxLayout(contactsPanel2, javax.swing.BoxLayout.Y_AXIS));
        contactsScrollPane.setViewportView(contactsPanel2);

        jPanel17.add(contactsScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 240, 120));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 310, 210));

        jLabel36.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(90, 133, 255));
        jLabel36.setText("Choisir un Destinataire");
        jPanel16.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 243, -1));

        chooseFile.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        chooseFile.setForeground(new java.awt.Color(51, 51, 51));
        chooseFile.setText("Parcourir");
        chooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFileActionPerformed(evt);
            }
        });
        jPanel16.add(chooseFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 90, 30));

        contactTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTextFieldActionPerformed(evt);
            }
        });
        jPanel16.add(contactTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 265, 20));
        jPanel16.add(filePathLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 265, 20));

        jPanel18.setBackground(new java.awt.Color(59, 184, 220,100));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 213, 255), 3));
        jPanel18.setForeground(new java.awt.Color(177, 185, 255));

        jLabel41.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 153, 153));
        jLabel41.setText("Document Envoyés");
        jPanel18.add(jLabel41);

        sentMessages.setColumns(20);
        sentMessages.setRows(5);
        sentMessages.setBorder(null);
        sentMessages.setMargin(new java.awt.Insets(80, 25, 1, 100));
        jScrollPane5.setViewportView(sentMessages);

        jPanel18.add(jScrollPane5);

        jPanel16.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 300, 210));

        jButton21.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton21.setForeground(new java.awt.Color(51, 51, 51));
        jButton21.setText("Envoyer");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 90, 30));

        jLabel42.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 153, 153));
        jLabel42.setText("Boite d'envoie");
        jLabel42.setToolTipText("");
        jPanel16.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 30));
        jPanel16.add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 200, -1));

        searchButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        searchButton.setForeground(new java.awt.Color(51, 51, 51));
        searchButton.setText("chercher pdf");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel16.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 110, 30));

        searchTextArea.setBackground(new java.awt.Color(255, 255, 255));
        searchTextArea.setLayout(new javax.swing.BoxLayout(searchTextArea, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(searchTextArea);

        jPanel16.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 230, 110));
        jPanel16.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, -1, -1));
        jPanel16.add(clickLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/flat-university-concept_23-2148172741.jpg"))); // NOI18N
        jPanel16.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        jLabel39.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 51, 51));
        jLabel39.setText("Destinataire");
        jPanel16.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 243, -1));

        jButton1.setText("leader d'opinion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, -1, -1));

        jTabbedPane5.addTab("tab2", jPanel16);

        jPanel2.add(jTabbedPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 560));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 910, 460));

        jButton11.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(51, 51, 51));
        jButton11.setText("Déconexion");
        jButton11.setMaximumSize(new java.awt.Dimension(87, 23));
        jButton11.setMinimumSize(new java.awt.Dimension(87, 23));
        jButton11.setName(""); // NOI18N
        jButton11.setPreferredSize(new java.awt.Dimension(87, 23));
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 110, 30));

        userLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userLabel.setForeground(new java.awt.Color(0, 186, 177));
        userLabel.setText("jLabel1");
        jPanel1.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/remplir-un-formulaire-dinscription-a-luniversite.jpg"))); // NOI18N
        jLabel2.setRequestFocusEnabled(false);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 455, 523));

        panel1.add(jPanel1);

        getContentPane().add(panel1);

        jMenuBar1.setBackground(new java.awt.Color(212, 213, 255));

        jMenu1.setForeground(new java.awt.Color(51, 51, 51));
        jMenu1.setText("options");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("leader d'opinion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(51, 51, 51));
        jMenu2.setText("à propos");

        jMenuItem3.setText("à propos de l'appication");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11MouseClicked

    // déconnexion 
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        
        GuiEvent gev=new GuiEvent(this,2);
        String emeteur = userLabel.getText();
        
        java.util.Map<String, Object> comptes= new java.util.HashMap<>();

        comptes.put("emeteur", emeteur) ; 
        
        gev.addParameter(comptes);
        agentaccueil.onGuiEvent(gev);


    }//GEN-LAST:event_jButton11ActionPerformed

    private void directoryLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directoryLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_directoryLabelActionPerformed

    // lieu de téléchargement
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
                
        JFileChooser choix = new JFileChooser();
        choix.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int retour = choix.showOpenDialog(this) ;
        
        if(retour==JFileChooser.APPROVE_OPTION){
            
           // chemin absolu du fichier choisi
           directoryLabel.setText(choix.getSelectedFile().toString()) ;
           System.out.println(directoryLabel.getText()) ;
        } 
        else
        {
           System.out.println("no file choosed") ;
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseClicked

    // choisir le fichier à envoyer
    private void chooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFileActionPerformed
        
        JFileChooser choix = new JFileChooser();
        int retour = choix.showOpenDialog(this) ;
        
        if(retour==JFileChooser.APPROVE_OPTION){
            
           // chemin absolu du fichier choisi
           filePathLabel.setText(choix.getSelectedFile().toString()) ;
           System.out.println(filePathLabel.getText()) ;
        } 
        else
        {
           System.out.println("no file choosed") ;
        }
    }//GEN-LAST:event_chooseFileActionPerformed
    
    // envoyer le message
    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        
        GuiEvent gev=new GuiEvent(this,1);
        String recepteur = contactTextField.getText();
        String emeteur = userLabel.getText();
        
        java.util.Map<String, Object> comptes= new java.util.HashMap<>();

        comptes.put("emeteur", emeteur) ; 
        comptes.put("recepteur", recepteur);
        
        gev.addParameter(comptes);
        agentaccueil.onGuiEvent(gev);

        Message m = new Message("55768",userLabel.getText(),contactTextField.getText()) ;

        m.setDocument(filePathLabel.getText()) ;
        m.setFichier(new File(m.getDocument())) ;

        MessageController mc = new MessageController() ;
        mc.insertMessage(m) ;
            
        sentMessages.append(m.getDocument()) ;
        
        
    }//GEN-LAST:event_jButton21ActionPerformed

    private void contactTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactTextFieldActionPerformed

    // recherch google
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

           GuiEvent gv = new GuiEvent(this,3) ;
           String searchTerm = searchTextField.getText() ; 
           Map<String,String> map = new HashMap<>() ; 
           map.put("searchTerm", searchTerm) ; 
           gv.addParameter(map) ;
           agentaccueil.onGuiEvent(gv) ;
        
           
    }//GEN-LAST:event_searchButtonActionPerformed
    
    // leader d'opinion
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
            leaderOpinion() ; 
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        JOptionPane.showMessageDialog(Accueil.this,"par Sassi Kahina, Bouhadouf Nassim, Sabrina","à propos",JOptionPane.INFORMATION_MESSAGE) ;
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            leaderOpinion() ; 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(false);
               
            }
        });
    }
    
    
    
    
    
    agentAccueil agentaccueil;

    public agentAccueil getAgentaccueil() {
        return agentaccueil;
    }

    public void setAgentaccueil(agentAccueil agentaccueil) {
        this.agentaccueil = agentaccueil;
    }

    
    // fixé l'utilisateur 
    public void setUser(String username){
        
        userLabel.setText(username) ;
    }
    
    //LISTE DES USERS
        public void showm(Etudiant etudiant){
       
            
            Font font = new Font("Segoe Script", Font.BOLD, 15);
            jTextArea8.setFont(font);
            jTextArea8.setForeground(Color.BLACK);
            jTextArea8.append(etudiant.getNom()+" "+etudiant.getPrenom()+" \n");

 /*           jTextArea4.setText(null);
            jTextArea4.setFont(font);
            jTextArea4.setForeground(Color.BLACK);
            jTextArea4.append(msg+" \n");*/
 
            
            JButton button_contact = new JButton(etudiant.getNom()+" "+etudiant.getPrenom()) ; 
            button_contact.addActionListener(new ActionListener()
            {
                @Override
                public void actionPerformed(ActionEvent e) {
                   contactTextField.setText(etudiant.getUsername().getUsername()) ;
                }
            });
            
            contactsPanel2.add(button_contact) ; 
            contactsPanel2.add(Box.createHorizontalStrut(25));
            contactsPanel2.revalidate() ; 
            contactsPanel2.repaint() ; 
            
        
    }
        //LISTE DESDOCUMENT
        public void showmdoclu(String msg){
       
            
            Font font = new Font("Segoe Script", Font.BOLD, 15);
            sentMessages.setFont(font);
            sentMessages.setForeground(Color.GREEN);
            sentMessages.append(msg+" \n");
            
        
    }
    
            public void showmdoNonclu(Message msg){
       
            
            /*jTextArea5.setText(null);
            Font font = new Font("Segoe Script", Font.BOLD, 15);
            jTextArea5.setFont(font);
            jTextArea5.setForeground(Color.RED);
            jTextArea5.append(msg+" \n");*/
            
            // bouton pour télécharger le fichier
            JButton button_msg = new JButton(msg.getDocument()) ; 
            button_msg.addActionListener(new ActionListener()
            {
                @Override
                public void actionPerformed(ActionEvent e) {
                    
                    try {
                        msg.download(directoryLabel.getText()) ;
                        msg.setLu(true) ;
                        MessageController mc = new MessageController() ;
                        mc.updateMessage(msg) ;
                        // message success
                        messageDownload.setText(msg.getDocument()+" a été téléchargé avec succès") ;
                        Font font = new Font("Segoe Script", Font.BOLD, 15);
                        messageDownload.setFont(font);
                        messageDownload.setBackground(Color.GREEN) ;
                        JButton source = (JButton) e.getSource() ;
                        source.setVisible(false) ;
                    } catch (IOException ex) {
                        Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
            
            messageReceivePanel.add(button_msg) ; 
            messageReceivePanel.add(Box.createHorizontalStrut(25));
            messageReceivePanel.revalidate() ; 
            messageReceivePanel.repaint() ; 
            
       
        
    }
    
    public void showGoogleSearch(ArrayList<GoogleResult> results)
    {
                   
                   for(GoogleResult result: results)
                   {
                    JButton b = new JButton(result.getLinkText()) ; 
                    b.setBackground(new Color(255,255,255)) ; 
                    b.setBorderPainted(false) ;
                    
                    b.addActionListener(new ActionListener()
                    {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            try {
                                Desktop.getDesktop().browse(new URI("https://google.com/"+result.getLinkHref()));
                            } catch (IOException | URISyntaxException ex) {
                                Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                      
                        
                 }) ; 
                    
                    searchTextArea.add(b) ; 
                    searchTextArea.add(Box.createVerticalStrut(20));
                    searchTextArea.revalidate() ; 
                    searchTextArea.repaint() ; 
                    
                    clickLabel.setText("clicker pour télécharger") ;
              }
        
                  
    }
     
    public void leaderOpinion()
    {
                       
            JDialog d = new JDialog(Accueil.this, "dialog Box"); 
            
            LeaderOpinion leader = new LeaderOpinion() ; 
            sprint3.entity.Etudiant etudiant = leader.getLeader() ; 
            
            JPanel box = new JPanel();
            box.setLayout(new BoxLayout(box, BoxLayout.Y_AXIS ));
            box.add(Box.createHorizontalStrut(10)) ; 
            JLabel l = new JLabel("Leader d'opinion") ; 
            l.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
            l.setForeground(new java.awt.Color(0, 153, 153));
            box.add(l); 
            box.add(Box.createVerticalStrut(30)) ;
            JLabel l2 = new JLabel("nom : "+etudiant.getNom()); 
            box.add(l2); 
            box.add(Box.createVerticalStrut(20)) ;
            JLabel l5 = new JLabel(" prenom : "+etudiant.getPrenom()); 
            box.add(l5); 
            box.add(Box.createVerticalStrut(20)) ;
            JLabel l3 = new JLabel("nombre de messages envoyés : "+leader.getNbMessages()) ; 
            box.add(l3); 
            box.add(Box.createVerticalStrut(20)) ;
            d.add(box) ; 
            d.setSize(300, 300); 
            d.setTitle("leader d'opinion") ;
            d.setVisible(true);
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseFile;
    private javax.swing.JLabel clickLabel;
    private javax.swing.JTextField contactTextField;
    private javax.swing.JPanel contactsPanel2;
    private javax.swing.JScrollPane contactsScrollPane;
    private javax.swing.JTextField directoryLabel;
    private javax.swing.JTextField filePathLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JLabel messageDownload;
    private javax.swing.JPanel messageReceivePanel;
    private java.awt.Panel panel1;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchTextArea;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JTextArea sentMessages;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
